/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package oucomp.indoorpos.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CombinedDomainXYPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYItemRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import oucomp.indoorpos.AccelRecord;

public class SpectrumPanel extends javax.swing.JPanel {

  // charting variable
  protected CombinedDomainXYPlot thePlot = null;
  protected XYPlot dataPlot;
  protected XYSeriesCollection dataSeriesCollection;
  protected JFreeChart theChart = null;
  protected ChartPanel chartPanel = null;

  public SpectrumPanel() {
    initComponents();
    createChart();
  }

  protected void createChart() {
    if (theChart == null) {
      System.out.println("[SpectrumPanel] Create Chart");
      thePlot = new CombinedDomainXYPlot(new NumberAxis("Frequency Spectral"));
      thePlot.setGap(40.0);
      thePlot.setOrientation(PlotOrientation.VERTICAL);
      // create sample subplot
      dataSeriesCollection = new XYSeriesCollection();
      dataPlot = new XYPlot(dataSeriesCollection, null, new NumberAxis("Strength"), new StandardXYItemRenderer());
      dataPlot.getRenderer().setSeriesPaint(0, Color.BLACK);
      dataPlot.getRenderer().setSeriesPaint(1, Color.YELLOW);
      dataPlot.setRangeAxisLocation(AxisLocation.BOTTOM_OR_LEFT);
      dataPlot.getRangeAxis().setRange(0, 25);
      thePlot.add(dataPlot, 1);
      // create chart
      theChart = new JFreeChart("IndoorPos DataSet",
              JFreeChart.DEFAULT_TITLE_FONT,
              thePlot, true);
      chartPanel = new ChartPanel(theChart, false);
      chartPanel.setPreferredSize(new Dimension(360, 120));
      this.add(chartPanel, BorderLayout.CENTER);
    }
  }

  public void setData(double sample[][], double mean[]) {
    if (sample == null || sample[0].length == 0) {
      return;
    }
    dataSeriesCollection.removeAllSeries();
    XYSeries dataSeries = new XYSeries("Frequency Spectral");
    for (int j = 0; j < sample[0].length; j++) {
      // skip the DC frequency = 0 point
      if (sample[0][j] > 0) {
        dataSeries.add(sample[0][j], sample[1][j]);
      }
    }
    dataPlot.getRangeAxis().setAutoRange(true);
    dataPlot.getDomainAxis().setRange(0, 10);
    dataSeriesCollection.addSeries(dataSeries);
    // mean
    XYSeries mSeries = new XYSeries("Mean");
    for (int j = 0; j < mean.length; j++) {
      mSeries.add(sample[0][j], mean[j]);
    }
    dataSeriesCollection.addSeries(mSeries);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setMinimumSize(new java.awt.Dimension(640, 360));
    setPreferredSize(new java.awt.Dimension(640, 360));
    setLayout(new java.awt.BorderLayout());
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
