package oucomp.falldetect;

import oucomp.falldetect.data.AccelDataset;
import oucomp.falldetect.data.AccelRecord;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.ListModel;

public class RecordSelectPanel extends javax.swing.JPanel {

  private AccelDataset theDataset = null;
  private RecordSelectListener listener = null;

  public RecordSelectPanel() {
    initComponents();
    DefaultListModel model = new DefaultListModel();
    jList1.setModel(model);
  }

  private void update() {
    jComboBox1.removeAllItems();

    if (theDataset == null) {
      return;
    }
    Iterator<String> it = theDataset.iterateRecordClass();
    while (it.hasNext()) {
      jComboBox1.addItem(it.next());
    }
  }

  public AccelDataset getDataset() {
    return theDataset;
  }

  public void setDataset(AccelDataset theDataset) {
    this.theDataset = theDataset;
    update();
  }
  
  public void setRecordSelectListener(RecordSelectListener listener) {
    this.listener = listener;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox();

    setLayout(new java.awt.GridBagLayout());

    jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        jList1ValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(jList1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weighty = 1.0;
    add(jScrollPane1, gridBagConstraints);

    jPanel1.setLayout(new java.awt.GridLayout(2, 1));

    jLabel1.setText("Select Data Class");
    jPanel1.add(jLabel1);

    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });
    jPanel1.add(jComboBox1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(jPanel1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    JComboBox cb = (JComboBox) evt.getSource();
    String recordClass = (String) cb.getSelectedItem();
    // populate the list
    if (theDataset == null) {
      return;
    }
    List<AccelRecord> recordList = theDataset.getDataSet(recordClass);
    if (recordClass == null) {
      return;
    }
    // get the model object from the list and clear it first
    DefaultListModel model = (DefaultListModel) jList1.getModel();
    model.removeAllElements();

    for (AccelRecord record : recordList) {
      model.addElement(record.getRecordLabel());
    }
  }//GEN-LAST:event_jComboBox1ActionPerformed

  private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
    if (evt.getValueIsAdjusting()) {
      return;
    }
    if (listener == null)
      return;
    int index = jList1.getSelectedIndex();
    ListModel model = jList1.getModel();
    if (index < 0 || index >= model.getSize())
      return;
    listener.recordSelected((String)jComboBox1.getSelectedItem(), (String)model.getElementAt(index));
  }//GEN-LAST:event_jList1ValueChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JList jList1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
